flix/vscode-flix

server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/handlers/util.ts
- Adds missing parameter to package commands
Fixes #26
=> fix: Package Commands

client/src/engine/jobs.ts, client/src/extension.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts
- Shows progress when running main and tests
- When finished with main, no longer shows a notification if it went well
- Shows output from tests and main in extension output
- Switches focus to extension output
- Shows how many tests passed and so on
Fixes #25 
Fixes #28
=> feat: Progress for runMain and runAllTests

client/src/extension.ts
=> fix: Adjust diagnostics

client/src/engine/jobs.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/server.ts
=> feat: Document Highlight Support

client/src/engine/jobs.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/handlers/util.ts, server/src/server.ts
- Refuses to run renames on document with errors
- Supposedly supported by compiler, but it gives wrong results if you rename a line that's changed after document last "worked"
Fixes #46
=> feat: Rename Support

server/src/handlers/handlers.ts, server/src/server.ts
=> feat: Improved rename support

client/src/extension.ts, client/src/handlers/handlers.ts, client/src/services/timers.ts, client/src/util/showStartupProgress.ts
=> feat: Improve timeout stability

server/src/engine/flix.ts, server/src/engine/queue.ts
=> fix: Process queue only when ready

client/src/extension.ts, client/src/util/ensureTargetWritable.ts
=> feat: Check if `./target` is writable

client/src/engine/jobs.ts, client/src/extension.ts, package.json, server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/engine/queue.ts, server/src/handlers/handlers.ts, server/src/server.ts
- Add flix.compileOnSave.enabled
- Add flix.compileOnChange.enabled
- Add flix.compileOnChange.delay
- Compile on save is no longer debounced
- Supports configuration changing while running
Fixes #66
=> feat: Support configuration of when to run compiler

syntaxes/flix.tmLanguage.json
Saw you missed a keyword when adding class and instance.
=> add sealed modifier

client/src/extension.ts, client/src/handlers/handlers.ts
=> Add support for Flix packages to runMain commands

client/src/handlers/handlers.ts
close #111 
If there are unsaved and modified files in workspace, a dialogue box pops up to ask whether to save the modified files or not.
=> save dirty buffers on run

client/src/handlers/handlers.ts, package-lock.json, package.json, server/src/engine/flix.ts
=> Add an additional setting for extra options to the Flix compiler

client/src/handlers/handlers.ts, client/src/util/showStartupProgress.ts
Increase timeout from 15s to 30s.
closes #128
=> Increase time limit for starting flix

AUTHORS.md, syntaxes/flix.tmLanguage.json, themes/FlixifyDark.json
The attached image shows before and after this change (lower half is before; upper half is after).
I agree to release this contribution under the Apache 2.0 license.
=> Syntax highlight type names and defs

client/src/engine/jobs.ts, client/src/extension.ts, server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/engine/queue.ts, server/src/handlers/handlers.ts, server/src/server.ts
Adds and uses `AddJar` and `RemJar` calls.
=> Add support for external JARs

client/src/util/ensureFlixExists.ts
Fix: #151
I have been able to test it on my computer, turns out it was simpler than it seemed to be.
=> fix: Handle new release checking failure

syntaxes/flix.tmLanguage.json
Fix: https://github.com/flix/vscode-flix/issues/187
=> feat: add missing annotations to syntax configuration file

syntaxes/flix.tmLanguage.json
https://github.com/flix/flix/issues/2904
=> feat: Add new keyword to syntax definition file

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
Fixes [#4042](https://github.com/flix/flix/issues/4042)
=> feat: add "Flix Package Manager: repl" command

syntaxes/flix.tmLanguage.json
Related to https://github.com/flix/flix/issues/4228
=> feat: add `for` and `yield` keywords

syntaxes/flix.tmLanguage.json
Related to https://github.com/flix/flix/issues/4224
=> feat: add `foreach` keyword

server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/handlers/util.ts, server/src/server.ts
https://github.com/flix/flix/pull/3415
The communication seems to work properly, I still need to add more functionalities to the provider to check whether everything is fine.
=> feat: inlay hints support

language-configuration.json
=> fix: use // instead of /// for line comments

package.json
Fixes https://github.com/flix/flix/issues/4492
=> feat: default tabs to 4 spaces

server/src/engine/flix.ts
uses the new `lsp` command
fixes #208
=> feat: pass LSP args to Flix

README.md
=> docs: Add note on the Flixify theme in readme

AUTHORS.md, client/package-lock.json, client/package.json, client/src/services/releases.ts, package-lock.json, package.json, server/package-lock.json, server/package.json
Closes https://github.com/flix/vscode-flix/issues/232
=> chore: upgrade package dependencies

.vscodeignore, build.js, package.json
This fixes https://github.com/flix/vscode-flix/pull/240#issuecomment-1380862531
=> fix: exclude unused files in the packaged extention for performance

server/src/engine/socket.ts
As expected, the issue with the restart action was caused by it closing the compiler, in turn calling another restart, which created a loop until something timed out. I tried to find a way to distinguish different close events (errors from premeditated socket.close() calls) but here I agree with https://github.com/flix/vscode-flix/pull/92#issuecomment-774709599, that this didn't immediately seem possible. I ended up making a solution with timestamps, which seems to work for what we need right now.
=> fix: Ensure that "Flix Restart" works

client/src/extension.ts
Solves https://github.com/flix/vscode-flix/issues/247
I wasn't sure about the message "Do you want to reload the flix ~~extention~~ extension   after changing flix.toml?", maybe this should be worded differently?
=> feat: ask to restart the compiler if `flix.toml` is updated

client/src/extension.ts, client/src/handlers/handlers.ts, client/src/services/releaseVirtualDocument.ts, client/src/services/timers.ts, client/src/util/ensureFlixExists.ts, client/src/util/showStartupProgress.ts, client/src/util/userMessages.ts, server/src/engine/flix.ts, server/src/engine/queue.ts, server/src/engine/socket.ts, server/src/handlers/handlers.ts, server/src/util/userMessages.ts
Solves https://github.com/flix/vscode-flix/issues/251
=> refactor: merge user messages into one file

client/src/engine/jobs.ts, client/src/extension.ts, client/src/handlers/handlers.ts, client/src/util/userMessages.ts, package.json, server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/server.ts
This should not be merged before the compiler side can handle the request. I'm currently working on the compiler side of this issue and by faking a few things I have been able to test that this commit should work.
=> feat: add `Show AST` button

syntaxes/flix.tmLanguage.json
=> fix: highlighting of holes

client/src/extension.ts, package.json
=> feat: add setting to toggle clearing of output

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
=> chore: remove `Flix: benchmark` command

.github/workflows/node.js.yml
=> ci: add Node v18 and v20

client/src/handlers/handlers.ts
I realize I need to think a bit more about this, but I'm just leaving this attempt here for now.
- This only looks at whether or not a terminal exists with the "REPL" name, not if it is actually running.
- When trying to `run` while no REPL-terminal exists, the `sendText(':eval ...')` isn't registered by the terminal unless a significant delay is added. 1s works but 100ms does not.
Fixes #258
=> fix: start new REPL if terminal closed

build.js, client/src/engine/jobs.ts, client/src/extension.ts, client/src/handlers/handlers.ts, client/src/services/releaseVirtualDocument.ts, client/src/services/releases.ts, client/src/services/state.ts, client/src/services/timers.ts, client/src/test/completion.test.ts, client/src/test/diagnostics.test.ts, client/src/test/helper.ts, client/src/util/createLanguageClient.ts, client/src/util/ensureFlixExists.ts, client/src/util/showStartupProgress.ts, client/src/util/userMessages.ts, server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/engine/queue.ts, server/src/engine/socket.ts, server/src/handlers/handlers.ts, server/src/handlers/util.ts, server/src/server.ts, server/src/util/javaVersion.ts, server/src/util/userMessages.ts
Apply configuration changes from #288
=> style: format all code with new config

client/src/services/releaseVirtualDocument.ts
=> fix: unable to get latest changelog

client/src/handlers/handlers.ts
=> fix: relaunch REPL on restart

syntaxes/flix.tmLanguage.json
=> fix: highlighting of unicode escapes

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
=> feat: add `doc` command

README.md, server/src/engine/flix.ts, server/src/util/userMessages.ts
=> feat: require Java 21

.github/workflows/code-checks.yml, .github/workflows/node.js.yml, .github/workflows/semantic-commit.yaml
Also removes tests for Node 14 and 16 as they are no longer supported
=> chore: upgrade actions

server/src/engine/flix.ts, server/src/util/userMessages.ts
=> Revert "feat: warn about source file being outside of project's scope"

client/package-lock.json, client/package.json, client/src/services/releases.ts, package-lock.json, package.json
=> Revert "refactor: replace node-fetch-commonjs with native fetch API"

server/src/engine/socket.ts, server/src/handlers/handlers.ts, server/src/handlers/util.ts
=> Revert "refactor: make response types more granular"

package.json, server/src/engine/flix.ts, server/src/engine/queue.ts, server/src/handlers/handlers.ts, server/src/server.ts
=> chore: remove debounce, compileOnSave, and compileOnChange options

server/src/server.ts
=> refactor: remove circular dependency workaround

client/testFixture/diagnostics.txt, test/printStdErr.flix.txt, test/printStdOut.flix.txt, test/triggerCrash.flix.txt
=> chore: remove remaining test code

.vscode/launch.json
=> chore: remove test launch config

client/src/extension.ts, package.json
=> feat: reactivate `Flix: init` command

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
=> feat: add `Flix: Start REPL` command

syntaxes/flix.tmLanguage.json
Related to https://github.com/flix/flix/issues/7331
=> feat: add new java import syntax

test/src/files.test.ts, test/src/hover.test.ts, test/src/util.ts, test/testWorkspace/src/Area.flix, test/testWorkspace/src/Main.flix
=> test: add tests for creating and deleting file

client/src/handlers/handlers.ts
=> fix: make the REPL terminal transient

package.json
=> fix: update minimum supported version of VS Code

test/src/files.test.ts, test/src/hover.test.ts
=> fix: update test cases

.github/workflows/node.js.yml, .vscode-test.js
=> test: run test suite in CI

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
=> feat: add `Flix: outdated` command

client/src/extension.ts, client/src/handlers/handlers.ts, package.json
=> feat: add `Flix: build-fatjar` command

.vscode-test.js, test/src/hover.test.ts, test/testWorkspace/latent/Broken.flix
=> test: hovering in broken project still shows info

test/src/diagnostics.test.ts, test/testWorkspace/latent/NameError.flix, test/testWorkspace/latent/RedundancyError.flix, test/testWorkspace/latent/ResolutionError.flix, test/testWorkspace/latent/SafetyError.flix, test/testWorkspace/latent/TypeError.flix, test/testWorkspace/latent/WeederError.flix
=> test: add tests for several different types of diagnostics

client/src/engine/jobs.ts, client/src/extension.ts, client/src/handlers/handlers.ts, server/src/engine/flix.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/server.ts, test/src/disconnect.test.ts
Dependent on:
- flix/flix#7563
Fixes #366
=> test: disconnect and reconnect to LSP

test/src/codeActions.test.ts, test/src/codeLenses.test.ts, test/src/completions.test.ts, test/src/diagnostics.test.ts, test/src/findReferences.test.ts, test/src/hover.test.ts, test/src/util.ts, test/testWorkspace/latent/UnusedFunction.flix, test/testWorkspace/src/Area.flix
=> test: add tests for most important providers

client/package-lock.json, client/package.json, client/src/extension.ts, client/src/handlers/handlers.ts, client/src/services/releases.ts, client/src/services/timers.ts, server/package-lock.json, server/package.json, server/src/engine/flix.ts, server/src/engine/queue.ts, server/src/engine/socket.ts, server/src/handlers/handlers.ts, server/src/util/javaVersion.ts
=> chore: remove uses of lodash

syntaxes/flix.tmLanguage.json
=> chore: remove `java_new`, `java_get_field` and `java_set_field` keywords

server/src/handlers/handlers.ts, server/src/handlers/util.ts, server/src/server.ts
=> feat: allow issuing commands in the presence of errors

server/src/engine/flix.ts
=> fix: 'cannot set userConfiguration on undefined' error message

.eslintrc.json, package-lock.json, package.json
=> chore: update dependencies

test/src/highlight.test.ts
=> test: update highlight test

syntaxes/flix.tmLanguage.json
=> feat: add `mut` keyword

syntaxes/flix.tmLanguage.json
=> feat: add `BigDecimal` literal highlighting

syntaxes/flix.tmLanguage.json
=> feat: reflect renaming of `debug` to `dbg`

test/src/highlight.test.ts
=> test: fix wrong ranges in highlight test

server/src/handlers/handlers.ts
=> fix: sync semanticTokenModifiers

client/src/engine/jobs.ts, server/src/engine/jobs.ts, server/src/handlers/handlers.ts, server/src/server.ts
=> feat: support SignatureHelp
