- client/src/engine/jobs.ts
- client/src/extension.ts
- server/src/engine/jobs.ts
- server/src/handlers/handlers.ts
- Add additional output window called "Flix Errors" (the other one is called "Flix Extension")
- When check runs successfully, show "Flix Errors" with "No errors"
- When check runs with errors, show "Flix Errors" with all `fullMessage` of the errors
Fixes #27 
Fixes #35
> feat: Show detailed diagnostics

- client/src/extension.ts
- client/src/services/releases.ts
- client/src/services/state.ts
- client/src/util/ensureFlixExists.ts
- Store currently installed version in global state
- When using workspace jar, do nothing
- When using global jar, check upon startup if a newer version is available
- Prompt user to download or skip
Fixes #49
> feat: Installation and Upgrades

- client/src/services/releases.ts
- client/src/util/ensureFlixExists.ts
- Save timestamp when fetching release
- If release was fetched under 30 minutes ago, don't fetch another one
Fixes #58
> feat: Skip fetch release if done recently

- server/src/handlers/handlers.ts
- Puts link to filename with failing test on same line
- Also makes it a clickable link
Should consider providing a link to non-failing test cases as well.
Fixes #53
> feat: Oneline all test, making links clickable/jumpable

- client/src/extension.ts
- client/src/handlers/handlers.ts
- package.json
fix #102 
For now, two methods are added:
Method 1: It simply checks whether there is an active terminal with the name `flix` in vscode window. If no, then it creates a new terminal named `flix` and compiles the flix program in that terminal. else it compiles in the existing terminal with the name `flix`.
Method 2: If there are no active terminals, it simply creates a new terminal named `flix` and compiles the program in it. If there are active terminals, then it opens a drop-down window in vscode to select a terminal to compile.
a sample drop-down to select a terminal:
> refactor "Run Main" to open a new terminal to compile the flix program

- client/src/handlers/handlers.ts
The program takes input from the user. If the input is not `undefined` (i.e. user has not pressed ESC), it creates a terminal and sends the command else does nothing.
fix #110
> Pressing ESC after clicking Run with args does not run the program

- client/src/extension.ts
- client/src/handlers/handlers.ts
- package.json
flix #103 
The following package commands are added:
1. init: `java -jar flix.jar init`
2. check: `java -jar flix.jar check`
3. build: `java -jar flix.jar build`
4. build-jar: `java -jar flix.jar build-jar`
5. build-pkg: `java -jar flix.jar build-pkg`
6. run: `java -jar flix.jar run`
7. benchmark: `java -jar flix.jar benchmark`
8. tests: `java -jar flix.jar test`
9. custom tests: `java -jar flix.jar test test01 test02 ...`
where `flix.jar` means the location of `flix.jar` file. and the input in custom tests is taken from the user.
> add package commands and run in a new terminal

- client/src/engine/jobs.ts
- client/src/extension.ts
- server/src/engine/flix.ts
- server/src/engine/jobs.ts
- server/src/engine/queue.ts
- server/src/handlers/handlers.ts
- server/src/server.ts
fix #107 
tested with the latest version of flix, working smoothly.
Only includes `fpkg` files which are in a directory named `lib`.
- `*/lib/package.fpkg` is included
- `*/lib/subdirectory/package.fpkg` is included.
- - `*/package.fpkg` is not included.
> Add Support for addPkg and RemPkg

- client/src/handlers/handlers.ts
- package.json
- server/src/engine/flix.ts
fix #108 
In the extension settings of vscode, a box in both `user` and `workspace` tabs is created which takes extra jvm arguments as input and passes these additional parameters to the run commands.
Settings in `user` tab apply globally to any instance of VS Code you open.
Settings in `workspace` tab are stored inside your workspace and only apply when the workspace is opened. 
That means, if JVM arguments of the `workspace` tab are null, the VS Code will consider the JVM arguments given in `User` tab.
> add option for additional jvm parameters

- client/src/extension.ts
- client/src/handlers/handlers.ts
close #106 
close #121 
Now there's only one output channel `Flix Compiler`
The messages which were previously sent to "Flix" are now sent to "Flix Compiler" and the "Flix" channel is now removed.
If an error occurs in the code:
> Merge "Flix" and "Flix Compiler" Terminals

- syntaxes/flix.tmLanguage.json
Also alphabetized the modifiers in that group
> Add `lawless` and `unlawful` modifiers to syntax highlighting

- syntaxes/flix.tmLanguage.json
- themes/FlixifyDark.json
The first image below shows what the highlighting looks like with this patch. (In particular, issue #133 is partially addressed. I think it's possible to address that issue fully by following [the approach taken in the builtin JavaScript extension](https://github.com/microsoft/vscode/blob/abff164c84d1075a9a09b7b36590183cd4f2e1c3/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L4701-L4721).)
The second image below shows that this patch fails to highlight simple function names that appear in multi-line pipes. I haven't yet figured out a way to match such names since VSCode only checks one line at a time unless one uses `begin` and `end` (which require the presence of some kind of delimiters).
By the way, the theme file mixed tabs and spaces, and I took the liberty of converting it …
> Highlight function calls, variables and more

- AUTHORS.md
- client/src/engine/jobs.ts
- server/src/engine/jobs.ts
- server/src/handlers/handlers.ts
- server/src/server.ts
Fix: #125
Add `lsp/documentSymbols` handler.
The request has been implemented in the language server here: https://github.com/flix/flix/pull/2289
It is still under development, as for now it returns just an hardcoded list of `DocumentSymbols`.
> Add support for DocumentSymbol to display outline and breadcrumbs (#125)

- client/src/engine/jobs.ts
- server/src/engine/jobs.ts
- server/src/handlers/handlers.ts
- server/src/server.ts
Add support [`lsp/workspaceSymbols`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_symbol)
This allows to search through the whole workspace for symbols. To try it press `ctrl` + `T`.
It has been tested with the SymbolProvider implemented  in https://github.com/flix/flix/pull/2385
> Add support for SymbolInformation and lsp/workspaceSymbols request.

- client/src/engine/jobs.ts
- server/src/engine/jobs.ts
- server/src/handlers/handlers.ts
- server/src/server.ts
Add support for `lsp/implementation` requests. This allows to [navigate](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-implementation) from a `class` to its `instances` by pressing `Cntrl + F12`.
See also: https://github.com/flix/flix/pull/2391
> Add support for lsp/implementation request

- syntaxes/flix.tmLanguage.json
Should address #160. 🙂 Here's a screenshot:
> Extend syntax highlighting for number literals

- syntaxes/flix.tmLanguage.json
As discussed in #133. The following screenshot shows the result with the current master version of Flix. 🙂
> Highlight the contents of ${...} recursively

- syntaxes/flix.tmLanguage.json
Should address #164. 🙂 Here's a screenshot showing the result:
> Highlight numbers with type suffix

- syntaxes/flix.tmLanguage.json
As discussed in #168. 🙂
Screenshot (not my favorite theme, but it uses many different colors):
> Syntax highlight pub as modifier and opaque as decl keyword

- client/src/extension.ts
- client/src/services/releaseVirtualDocument.ts
- client/src/services/releases.ts
- client/src/services/state.ts
- client/src/util/ensureFlixExists.ts
- package.json
Fix: #146
As for now, every time the compiler is updated, a new document (plaintext) is displayed in the editor containing the version of the compiler and the changelog as it is written in the release page. The changelog is displayed as a readonly document thanks to the [virtual document API](https://code.visualstudio.com/api/extension-guides/virtual-documents)
We could discuss whether this behavior is however disturbing for the user because it may interrupt an user reading some code while the extension is loading for example. However it is true that at this point the extension is still loading. To address the potential issue, we could substitute the current behavior with a notification having an open button which when clicked will open the document.
Note: This PR builds on top of …
> Show changelog on compiler update

- client/package-lock.json
- client/package.json
- client/src/extension.ts
- server/package-lock.json
- server/package.json
#203
* Update definitions for vscode-languageclient and vscode-languageserver.
* Update client start to match new API.
Still missing:
* handler registration, do we want to change the current registration strategy? Now it's possible to register handlers before the extension is started.
* dispose handlers
* check the other points of the list https://github.com/Microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server
> feat: update vscode-languageclient and vscode-languageserver to 8.0.1

- server/src/util/javaVersion.ts
The current code relies on the JVM's default classpath (the current dir), which is used when the CLASSPATH environment variable is not set.
The CLASSPATH variable might be set globally or in my case set by another vscode plugin (e.g. nix-environment-selector) and then cause the invocation of `CheckJavaVersion` to fail with a hard-to-debug error even when jdk 11+ is installed: 
```Flix requires Java 11 or later. Found "unknown version".```
The added '-cp' command line parameter is available at least from jdk7 (https://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html#CBBIAJDA)
There is some overlap with https://github.com/flix/vscode-flix/pull/93, but this has a conflict and seems abandoned.
I agree to release my contributions under Apache 2.
> fix: Specify the classpath for the version check explicitly

- package-lock.json
- package.json
eventually this closes https://github.com/flix/vscode-flix/issues/70
This PR introduces [esbuild](https://github.com/evanw/esbuild) as a project bundler. Esbuild is built on Go, allowing it to get extremely good compile times. 
Also for the Flix extension to be used in a vscode web environments like [github.dev](https://github.dev/) and [vscode.dev](https://vscode.dev/) we will need to use a bundler, since vscode can only load a single file for an extension when running in a browser.
I wasn't quite sure of the best way to test this PR. When building the project, I get no errors (and I get the bundled `client/out/extension.js` file), and when launching the extension, it works like usual.
> chore: add esbuild bundler

- client/src/extension.ts
- client/src/handlers/handlers.ts
When running my tests this worked as expected, and the value of `context.globalStorageUri.fsPath` was the excact same as the value of `context.globalStoragePath`. This PR is a duplicate of https://github.com/flix/vscode-flix/pull/207, hence this change should close both.
> refactor: remove deprecated globalStoragePath, use globalStorageUri instead

- client/src/handlers/handlers.ts
- package.json
- server/src/engine/flix.ts
Eventually this solves https://github.com/flix/vscode-flix/issues/152
This solution works for the compiler used to run the flix programs, but the compiler which compiles on-changes and on-saves seems to use the `--explain` flag as default, and I haven’t been able to find out where this is set.  
This means that this solution works when a program is run and for instance when the :check command is executed, but it’s currently not possible to not get the compiler for on-change and on-safe to not use the `--explain` flag.
Example of the compile on-change without explicitly setting the `--explain` flag:
> feat: Added option to toggle `--explain` flag

- server/src/engine/flix.ts
- server/src/engine/socket.ts
This explores the option to simply reconnect to the socket once the connection is lost due to standby instead of restarting the entire flix compiler, which takes longer.
I will have to run a couple more tests later today to make sure this works, but initially it seems to work.
> fix: reconnect instead of restart when connection is lost due to standby

- server/src/engine/socket.ts
This is related to the issue (https://github.com/flix/vscode-flix/pull/245#issuecomment-1410758239) where, if the java process died, we would log an error but not restart the flix compiler.
This solution restarts the compiler if the socket connection is closed and the client listener is no longer active. It does not remove the logged error.
> (I guess we have to be careful with multiple instances of VSCode running multiple instances of the Flix compiler.) https://github.com/flix/vscode-flix/pull/245#issuecomment-1410745090
I tested this and it still seems to work. I had two VSCode running multiple instances of the Flix compiler and then i killed one of the java processes, and only that instance began to restart its flix compiler.
> fix: restart compiler when the java process dies

- server/src/engine/flix.ts
- server/src/util/javaVersion.ts
Solves https://github.com/flix/vscode-flix/issues/198
This solution does not actually check if some JDK is on PATH but it simply sends an error if we are not able to run a Java statement or find a major Java version. Maybe this could also be our solution to https://github.com/flix/vscode-flix/pull/248 if we somehow included JAVA_HOME in the error message?
> fix: changed the error message for when we don't find a major java version

- AUTHORS.md
- client/src/handlers/handlers.ts
> fix: pass 'extraFlixArgs' when creating shared REPL

- syntaxes/flix.tmLanguage.json
This classifies the `branch` and `jumpto` as "keyword.control.ast.flix". 
This colors it red in the 'Flixify Dark' theme:
And purple in the default theme:
Fixes #272
> feat: highlight `branch` and `jumpto` syntax

- syntaxes/flix.tmLanguage.json
> fix: highlighting of identifiers in ASTs

- syntaxes/flix.tmLanguage.json
> chore: remove `rel` and `lat` keywords

- client/package-lock.json
- client/package.json
- client/src/services/releases.ts
> Revert "chore: swap out node-fetch-commonjs with node-fetch"

- client/package-lock.json
- client/package.json
- client/src/services/releases.ts
- package-lock.json
- package.json
> refactor: replace node-fetch-commonjs with native fetch API

- README.md
- syntaxes/flix.tmLanguage.json
> chore: add `trait` keyword, drop `class` keyword

- syntaxes/flix.tmLanguage.json
> chore: drop `resume` keyword

- syntaxes/flix.tmLanguage.json
> chore: drop `for` keyword

- .gitignore
When running `npx @vscode/vsce package` a file named something like `flix-1.18.0.vsix` is output to the root directory.
> chore: add built extension file to `.gitignore`

- client/src/extension.ts
- client/src/handlers/handlers.ts
- package-lock.json
- package.json
> feat: launch REPL as own shell

- .gitignore
Ignore the generated `lib` folder in the test workspace.
> chore: add `lib` to gitignore

- .github/workflows/ci.yml
Avoids running stuff like packaging and code style checking multiple times, when the outcome should not depend on the matrix.
This also makes it easier to target a specific job for local debugging.
NOTE: This removes testing with Node 18. This should not matter as Node is only used for the build process, and is not part of the tested product.
> ci: split `check` job into multiple

- server/src/handlers/handlers.ts
The extension should now send a completion request to LSP server when typing `#`.
Related to https://github.com/flix/flix/pull/7916
> feat: update trigger characters with `#` for records

- syntaxes/flix.tmLanguage.json
> chore: drop `ref` and `deref` keywords

- syntaxes/flix.tmLanguage.json
> chore: drop `do` keyword

- syntaxes/flix.tmLanguage.json
> feat: highlight function- and struct arrow differently

- test/src/highlight.test.ts
This PR modifies the highlight tests regarding enum cases. Before, they expected the parameters to be included in the highlight. For instance, for `case Circel(Int32)` previously `Circle(Int32)` would be highlighted, whereas now only `Circle` will be.
Related to flix/flix#9114
> fix: highlight tests shouldn't expect case parameters to be included in case highlight

- test/src/highlight.test.ts
This PR skips the highlight record test. This will be temporary until a fix for record highlighting has been implemented.
> refactor: skip record highlight test until follow record fix

- test/src/diagnostics.test.ts
- test/src/highlight.test.ts
- test/testWorkspaces/codeActions/src/Dividable.flix
- test/testWorkspaces/findReferences/src/Dividable.flix.old
- test/testWorkspaces/goto/src/Rewind.flix
- test/testWorkspaces/highlight/src/Dividable.flix.old
- test/testWorkspaces/implementation/src/Dividable.flix.old
> test: reflect language changes

- test/src/codeActions.test.ts
These have been changed in the compiler on the master branch.
We're in this annoying cyclic dependency situation until the next version of the compiler is published, so it's just a question of which CI should be failing until then.
> test: update code action titles

- test/src/findReferences.test.ts
This PR changes a few tests of the "find references", particularly in relation to the changes in behaviour due to the work happening at flix/flix#9449. Here, I will list the changes.
1. The tests regarding enum cases expected the references to contain `SourceLocation`s for the entire enum cases (including the parameters), where it ought to expect just the `SourceLocation` for the case symbols. This has been adjusted.
2. The tests for signatures never expected the implementations of them as references. I'd argue that, at least when finding the references to the signature from the declaration site, the result should include the implementing definitions. So the tests have been adjusted to expect this. Additionally, it could maybe be argued that finding the references to the signature from a …
> fix: find reference tests relying on wrong expected behaviour

- client/src/handlers/handlers.ts
- addresses #486 
- I added the flag and believe that the errors should go away and it doesn't affect lower jdk versions 
- output from the vscode extension debugging window
```
Found `flix.toml`. Checking dependencies...
Resolving Flix dependencies...
Downloading Flix dependencies...
Resolving Maven dependencies...
Running Maven dependency resolver.
Downloading external jar dependencies...
Dependency resolution completed.
__   _   _
/ _| | | (_)            Welcome to Flix 0.59.0
| |_  | |  _  __  __
|  _| | | | | \ \/ /     Enter an expression to have it evaluated.
| |   | | | |  >  <      Type ':help' for more information.
|_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.
flix>
```
> refactor: add java flag to prevent warnings with jdk 24

- client/src/extension.ts
- client/src/handlers/handlers.ts
Old implementation tried making a new file open.
Now it creates a notification of the path of pretty printed AST.
Addresses #485.
> refactor: ShowAST creates ast file and gives notification of file path
